version: '3'

volumes:
  production_mysql_data: {}
  production_mysql_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cz_api_production_django
    platform: linux/x86_64
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start
  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: cz_api_production_mysql
    container_name: mysql
    volumes:
      - production_mysql_data:/var/lib/mysql:z
      - production_mysql_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.mysql

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cz_api_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:6
