# Generated by Django 3.2.15 on 2023-11-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
