# Generated by Django 3.2.15 on 2023-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cz', '0003_auto_20231117_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtypeid', models.IntegerField()),
                ('typetier', models.IntegerField()),
                ('special', models.IntegerField()),
                ('level', models.IntegerField()),
                ('regionid', models.IntegerField()),
                ('featuredweek', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('invoice', models.IntegerField()),
                ('dataconvert', models.IntegerField()),
            ],
            options={
                'db_table': 'eventlink',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Eventtournament',
        ),
    ]
