# Generated by Django 3.2.15 on 2023-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cz', '0004_auto_20231126_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoregame',
            fields=[
                ('gameid', models.IntegerField(primary_key=True, serialize=False)),
                ('drawid', models.IntegerField()),
                ('teamid1', models.IntegerField()),
                ('teamid2', models.IntegerField()),
                ('teamid_top', models.IntegerField()),
                ('teamid_bottom', models.IntegerField()),
                ('profileid1', models.IntegerField()),
                ('profileid2', models.IntegerField()),
                ('hammer', models.IntegerField()),
                ('numends', models.IntegerField()),
                ('teamid1_colour', models.CharField(max_length=10)),
                ('teamid2_colour', models.CharField(max_length=10)),
                ('teamid1_draw', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid2_draw', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid1_draw_two', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid2_draw_two', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid1_draw_three', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid2_draw_three', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid1_draw_four', models.DecimalField(decimal_places=2, max_digits=9)),
                ('teamid2_draw_four', models.DecimalField(decimal_places=2, max_digits=9)),
                ('skipid1', models.IntegerField()),
                ('fourthid1', models.IntegerField()),
                ('thirdid1', models.IntegerField()),
                ('sectionid1', models.IntegerField()),
                ('skipid2', models.IntegerField()),
                ('fourthid2', models.IntegerField()),
                ('thirdid2', models.IntegerField()),
                ('sectionid2', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('local_gameid', models.IntegerField()),
                ('fantasy_email', models.IntegerField()),
                ('tweet_end_by_end', models.IntegerField()),
                ('threadid', models.IntegerField()),
                ('length', models.IntegerField()),
                ('streamcount', models.IntegerField()),
            ],
            options={
                'db_table': 'scoregame',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournamentgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamelinkid', models.IntegerField()),
            ],
            options={
                'db_table': 'tournamentgame',
                'managed': False,
            },
        ),
    ]
